<?php

$lang_Backup = array(

// Errors
'E_NeverDefinedSaveDB'    	=>	'You never defined a method to save the database!',
'E_DBNotSupported'			=>	'Your database is currently not supported.',
'E_NoDirectorySpecified'	=>	'You never specified a directory to save to.',
'E_CantFindDirectory'		=>	'I was unable to find the specified directory, make sure it exists first.',
'E_UnableToWriteToDirectory'=>	'I was unable to write to the specified directory, try chmodding it correctly.',
'E_CouldNotConnect'			=>	'I was unable to connect to the host specified.',
'E_UnableToLogin'			=>	'I was unable to login with the username and password specified',
'E_UnableToUpload'			=>	'I was unable to upload the file, perhaps you\'re out of space or do not have adaquete permissions?',
'E_InvalidMethod'			=>	'The method you selected was invalid.',
'E_WriteAccessNeeded'		=>	'Write access must be avalaible to this directory',

// Headers
'H_Backup'					=>	'PunBB Backup',
'H_BackupDB'				=>	'Backup Database',
'H_BackupMethod'			=>	'Choose backup method',

// Inputs
'Input_Host'				=>	'Host: ',
'Input_User'				=>	'Username: ',
'Input_Pass'				=>	'Password: ',

// Descriptions
'Desc_1'					=>	'This plugin allows you to quickly and easily make backups of your database data locally, to your computer or to an external FTP server.',
'Desc_2'					=>	'Making regular backups is very important, as it allows you to quickly and easily restore your site to its former self if you make a mistake or get hacked. Its recommended you make backups every 24 hours and before you make any major changes to the site (installing the latest PunBB version, installing a mod, etc).',
'Desc_3'					=>	'Currently, MySQL, MySQLi and SQLite have full support for dumping stucture and data. PostgreSQL is also supported, but only data may be dumped.',
'Desc_Download'				=>	'Download the database backup to your local harddrive.',
'Desc_FileSystem'			=>	'Save it onto the servers filesystem.',


// Messages
'M_Server'					=>	' server.',
'M_CreatingBackup'			=>	'Creating your backup may take a while, especially on large forums. Don\'t be suprised if it takes several minutes for the next page to appear.',
'M_SQLDumpStartedAt'		=>	'-- SQL dump commenced at ',
'M_GeneratedBy'				=>	'-- Generated by PunBB Backup Plugin',
'M_SaveBackup'				=>	'Save this backup to an ',
'M_DumpingDB'				=>	'-- Dumping database `',
'M_DBType'					=>	'` - Database type: ',
'M_DumpEndedAt'				=>	'-- SQL dump concluded at ',
'M_BackupSuccessful'		=>	'A backup has successfully been written to the local filesystem!',
'M_UploadSuccessful'		=>	'Upload Successful!',
'M_BackupUploaded'			=>	'A backup has successfully been uploaded to "',

// Options
'O_GoBack'					=>	'Go back',
'O_Download'				=>	'Download',
'O_FileSystem'				=>	'Filesystem',
'O_Directory'				=>	'Directory: ',
'O_FTP'						=>	'FTP',

);?>